# Generated by Django 3.0.14 on 2024-04-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
